version: '3.8'
services:

  # Nginx configuration
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./docker/duckdnscerts:/etc/ssl/certs
      - ./nginx/conf.d:/etc/nginx/conf.d
      # - ./certbot/conf:/etc/letsencrypt
      # - ./certbot/www:/var/www/certbot
    depends_on:
      - website
    restart: unless-stopped
    command: nginx -g "daemon off;"

  # Certbot configuration - Currently WIP
  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   restart: unless-stopped
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # Website container
  website:
    build: 
      context: ./website
      dockerfile: website.Dockerfile
    volumes:
      - ./website:/website
    restart: unless-stopped