version: '3.8'
services:

  # Website container
  website:
    build: 
      context: ./website
      dockerfile: website.Dockerfile
    ports:
      - "3000:3000"
    # environment:
    #   - DB_HOST=${DB_HOST}
    #   - DB_PORT=${DB_PORT}
    #   - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./website:/website
    restart: always