version: '3.8'
services:

  # Nginx configuration
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - web
    depends_on:
      - website
    restart: unless-stopped

  # Website container
  website:
    build: 
      context: ./website
      dockerfile: website.Dockerfile
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    driver: bridge
  