name: Global Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-compose-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker Image
      run: |
        docker-compose build

    - name: Run Docker Compose
      run: |
        docker-compose up -d

    - name: Run Docker Compose Down
      run: |
        docker-compose down
