name: Global Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-compose-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Clone the required repositories
      run: |
        git clone https://github.com/aurruti/despesapp

    - name: Build Docker Image
      run: |
        docker compose build

    - name: Create Required Directories and Certificates
      run: |
        mkdir -p certbot/conf
        mkdir -p certbot/www
        # Create temporary self-signed cert for testing
        mkdir -p certbot/conf/live/aurruti.cat
        openssl req -x509 -nodes -newkey rsa:4096 -days 1 \
          -keyout certbot/conf/live/aurruti.cat/privkey.pem \
          -out certbot/conf/live/aurruti.cat/fullchain.pem \
          -subj '/CN=localhost'
    
    - name: Create necessary (empty) .env files
      run: |
        cp despesapp/services/env.txt despesapp/services/.env

    - name: Run Docker Compose
      run: |
        docker compose up -d

    - name: Run Docker Compose Down
      run: |
        docker compose down
