name: Scripts Build

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/**'
      - '.github/workflows/scripts.yml'
      - 'docker-compose.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'scripts/**'
      - '.github/workflows/scripts.yml'
      - 'docker-compose.yml'

jobs:
  scripts-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t scripts-app -f scripts/scripts.Dockerfile ./scripts
