name: Scripts Test

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/**'
  pull_request:
    branches:
      - main
    paths:
      - 'scripts/**'

jobs:
  scripts-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
      
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Clone Despesapp Repository
      run: |
        git clone https://github.com/aurruti/despesapp
  
    - name: Test scripts
      run: |
        for script in ./scripts/*.sh; do
          bash "$script"
        done
